---
ansible_become: true
os_id: '{{ ansible_lsb.id.lower() }}'
os_code: '{{ ansible_lsb.codename.lower() }}'

version:
  containerd: 1.2.13-1
  docker: "5:19.03.8~3-0~{{ os_id }}-{{ os_code }}"

docker:
  apt_key_id: 8D81803C0EBFCD88
  apt_key_url: "https://download.docker.com/linux/{{ os_id }}/gpg"
  apt_repository:
    "deb https://download.docker.com/linux/{{ os_id }} {{ os_code }} stable"

daemon:
  registry-mirrors: ["https://docker-mirror.pikube.dev:32443"]
  # data-root: "/var/lib/docker"
  exec-opts: ["native.cgroupdriver=systemd"]
  storage-driver: "overlay2"
  log-driver: "json-file"
  log-opts:
    max-size: "100m"
    max-file: "3"
