---
- name: apt-get update
  apt:
    force_apt_get: true
    update_cache: true

# Don't use systemd ansible command; it drops the ssh connection and fails
- name: restart containerd
  shell: |
    systemctl enable containerd.service
    systemctl restart containerd.service
    systemctl is-active containerd.service
  async: 1
  poll: 0
