---
- name: apt-get update
  apt:
    force_apt_get: true
    update_cache: true

# Don't use systemd ansible command; it drops the ssh connection and fails
- name: restart Docker
  shell: |
    systemctl daemon-reload
    systemctl enable docker.service
    systemctl restart docker.service
    systemctl is-active docker.service
  async: 1
  poll: 0
