---
- name: Make sure ansible_lsb is set
  assert:
    that:
      - ansible_lsb.id is defined
      - ansible_lsb.codename is defined
    fail_msg: "Please install 'lsb-release' or equivalent"

- name: add apt-key for Docker
  apt_key:
    id: "{{ docker.apt_key_id }}"
    url: "{{ docker.apt_key_url }}"

- name: add apt-repository for Docker
  apt_repository:
    repo: "{{ docker.apt_repository }}"
  notify: apt-get update

- meta: flush_handlers

- name: unhold Docker for updates
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  with_items:
    - containerd.io
    - docker-ce
    - docker-ce-cli

- name: install Docker
  apt:
    force_apt_get: true
    install_recommends: false
    name:
      - "containerd.io={{ version.containerd }}"
      - "docker-ce={{ version.docker }}"
      - "docker-ce-cli={{ version.docker }}"
  notify: restart Docker

- name: hold Docker updates
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - containerd.io
    - docker-ce
    - docker-ce-cli

- name: ensure etc/docker directory exists
  file:
    path: /etc/docker
    recurse: true
    state: directory

- name: install Docker daemon configuration
  template:
    dest: /etc/docker/daemon.json
    src: daemon.json.j2
  notify: restart Docker

- name: Add user 'pi' to the 'docker' group
  user:
    name: pi
    groups: docker
    append: yes

- meta: flush_handlers
