---
- hosts:
    - pikube-master
  roles:
    - raspberry_pi
    - nfs-server
    - containerd
    - kubernetes_common
    - kubernetes_master
- hosts:
    - pikube-node-01
    # - pikube-node-02
    # - pikube-node-03
  roles:
    - raspberry_pi
    - containerd
    - kubernetes_common
    - kubernetes_node
