---
ansible_become: true
os_id: '{{ ansible_lsb.id.lower() }}'
os_code: '{{ ansible_lsb.codename.lower() }}'

version:
  containerd: 1.6.18-1

docker:
  apt_key_id: 8D81803C0EBFCD88
  apt_key_url: "https://download.docker.com/linux/{{ os_id }}/gpg"
  apt_repository:
    "deb https://download.docker.com/linux/{{ os_id }} {{ os_code }} stable"
