---
- name: register k8s token
  changed_when: false
  local_action: command cat build/k8s-token
  register: k8s_token
  run_once: true
  vars:
    ansible_become: false

- name: register k8s address
  args:
    warn: false
  changed_when: false
  command: |
    sed -n -E -e \
    's/^ +server: +https?:\/\/([^\/]+)$/\1/p' \
    build/k8s-config.yaml
  delegate_to: localhost
  register: k8s_address
  run_once: true
  vars:
    ansible_become: false

- name: kubeadm join
  command: |
    kubeadm \
      join '{{ k8s_address.stdout }}' \
      --token '{{ k8s_token.stdout }}' \
      --discovery-token-unsafe-skip-ca-verification
  args:
    creates: /etc/kubernetes/kubelet.conf
